/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bladerfRadarMIMO.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(557afc09e113d01c70b70472158e45f8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sfcwRadar/bladerfRadarMIMO.h>
// pydoc.h is automatically generated in the build directory
#include <bladerfRadarMIMO_pydoc.h>

void bind_bladerfRadarMIMO(py::module& m)
{

    using bladerfRadarMIMO    = gr::sfcwRadar::bladerfRadarMIMO;


    py::class_<bladerfRadarMIMO, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<bladerfRadarMIMO>>(m, "bladerfRadarMIMO", D(bladerfRadarMIMO))

        .def(py::init(&bladerfRadarMIMO::make),
           D(bladerfRadarMIMO,make)
        )
        



        ;




}








