/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bladerfRadarBurst_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7298d1f653c97ab2a592dbc23eaef83a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sfcwRadar/bladerfRadarBurst_cc.h>
// pydoc.h is automatically generated in the build directory
#include <bladerfRadarBurst_cc_pydoc.h>

void bind_bladerfRadarBurst_cc(py::module& m)
{

    using bladerfRadarBurst_cc    = gr::sfcwRadar::bladerfRadarBurst_cc;


    py::class_<bladerfRadarBurst_cc, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<bladerfRadarBurst_cc>>(m, "bladerfRadarBurst_cc", D(bladerfRadarBurst_cc))

        .def(py::init(&bladerfRadarBurst_cc::make),
           D(bladerfRadarBurst_cc,make)
        )
        
        .def("set_rx_gain", &bladerfRadarBurst_cc::set_rx_gain,
                py::arg("gain"),
                D(bladerfRadarBurst_cc,set_rx_gain)
        )
        
        .def("set_ref_gain", &bladerfRadarBurst_cc::set_ref_gain,
                py::arg("gain"),
                D(bladerfRadarBurst_cc,set_ref_gain)
        )
        .def("set_tx_gain", &bladerfRadarBurst_cc::set_tx_gain,
                py::arg("gain"),
                D(bladerfRadarBurst_cc,set_tx_gain)
        )

        ;




}








