/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sfcw_radar_miso_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(da59a1a6ed52c398d55bb4a82e6b2ff6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sfcwRadar/sfcw_radar_miso_cc.h>
// pydoc.h is automatically generated in the build directory
#include <sfcw_radar_miso_cc_pydoc.h>

void bind_sfcw_radar_miso_cc(py::module& m)
{

    using sfcw_radar_miso_cc    = gr::sfcwRadar::sfcw_radar_miso_cc;


    py::class_<sfcw_radar_miso_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<sfcw_radar_miso_cc>>(m, "sfcw_radar_miso_cc", D(sfcw_radar_miso_cc))

        .def(py::init(&sfcw_radar_miso_cc::make),
           D(sfcw_radar_miso_cc,make)
        )
        



        ;




}








