/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-sfcwRadar
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SFCWRADAR_API_H
#define INCLUDED_SFCWRADAR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_sfcwRadar_EXPORTS
#define SFCWRADAR_API __GR_ATTR_EXPORT
#else
#define SFCWRADAR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SFCWRADAR_API_H */
